# Generated by Django 5.1.6 on 2025-03-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("solarapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="roles",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
