# Generated by Django 5.1.6 on 2025-03-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solarapp", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="role",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="solarapp.role"
            ),
        ),
    ]
