# Generated by Django 5.1.6 on 2025-05-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0004_role_remove_userprofile_role_userprofile_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('properties', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('invited_emails', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
