# Generated by Django 5.1.6 on 2025-05-04 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0005_solarplant'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solarapp.solarplant'),
        ),
    ]
