# Generated by Django 5.1.6 on 2025-05-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0006_userprofile_assigned_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='assigned_plant',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_plants',
            field=models.ManyToManyField(blank=True, related_name='users', to='solarapp.solarplant'),
        ),
    ]
