# Generated by Django 5.1.6 on 2025-05-04 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0008_solarplant_collected_at_solarplant_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solarplant',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='plants', to=settings.AUTH_USER_MODEL),
        ),
    ]
