# Generated by Django 5.2.1 on 2025-05-12 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0009_solarplant_assigned_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('weather', models.CharField(blank=True, max_length=100)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('collected_date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='solarapp.solarplant')),
            ],
        ),
    ]
