# Generated by Django 5.2.1 on 2025-05-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0010_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
