# Generated by Django 5.2.1 on 2025-05-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0012_userprofile_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='approved',
        ),
    ]
