# Generated by Django 5.1.6 on 2025-06-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solarapp", "0014_alter_role_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarplant",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solarplant",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
