# Generated by Django 5.1.6 on 2025-06-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solarapp", "0015_solarplant_latitude_solarplant_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarplant",
            name="status",
            field=models.CharField(
                choices=[
                    ("In process", "In process"),
                    ("Completed", "Completed"),
                    ("Delayed", "Delayed"),
                ],
                default="In process",
                max_length=20,
            ),
        ),
    ]
